#!/bin/bash
. ./scripts/docker-machine-common.sh

export DOCKER_MACHINE_AWS_OWNER="${DOCKER_MACHINE_AWS_OWNER}"
export DOCKER_MACHINE_AWS_CATEGORY="${DOCKER_MACHINE_AWS_CATEGORY}"
export DOCKER_MACHINE_AWS_REGION="${DOCKER_MACHINE_AWS_REGION:-us-east-1}"
export DOCKER_MACHINE_AWS_INSTANCE_TYPE="${DOCKER_MACHINE_AWS_INSTANCE_TYPE:-m3.medium}"
export DOCKER_MACHINE_AWS_NAME_FILE="${DOCKER_MACHINE_NAME_FILE:-.docker-machine-aws}"
export DOCKER_MACHINE_AWS_SG_NAME="${DOCKER_MACHINE_AWS_SG_NAME:-pcf-dev-docker-machine-containers-broker}"